# Generated by Django 4.2.3 on 2023-07-19 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='sektor nomi')),
            ],
            options={
                'verbose_name': 'sektor',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='mahalla nomi ')),
                ('sector', models.ForeignKey(help_text='Mahalla qaysi sektorga tegishli ekanligini tanlang', on_delete=django.db.models.deletion.PROTECT, to='mahalla.sector')),
            ],
            options={
                'verbose_name': 'Mahalla',
                'verbose_name_plural': 'Mahalalar',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25, verbose_name='F.I.O')),
                ('passport', models.CharField(max_length=20, verbose_name='Passport seriyasi')),
                ('birthdate', models.DateField(verbose_name="tug'ilgan sanasi")),
                ('gender', models.CharField(choices=[('male', 'erkak'), ('female', 'ayol')], max_length=250, verbose_name='Fuqoro jinsi')),
                ('educated', models.CharField(choices=[('middle', "o'rta ma'lumotli"), ('senior', 'oliy malumotli')], max_length=250, verbose_name="Fuqoro ma'lumoti")),
                ('adress', models.TextField(verbose_name='yashash manzili')),
                ('iron_note', models.CharField(choices=[('yes', 'ha'), ('no', "yo'q")], max_length=250, verbose_name='Temir daftarga kiritilganmi?')),
                ('abroad', models.CharField(choices=[('yes', 'ha'), ('no', "yo'q")], max_length=250, verbose_name='Chet eldami')),
                ('disabillity', models.CharField(choices=[('yes', 'ha'), ('no', "yo'q")], max_length=20, verbose_name='Nogironligi bormi?')),
                ('women_note', models.CharField(choices=[('yes', 'ha'), ('no', "yo'q")], max_length=250, verbose_name='Ayollar daftariga kiritilganmi?')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mahalla.neighborhood', verbose_name='mahallani tanlang')),
            ],
            options={
                'verbose_name': 'Fuqoro',
                'verbose_name_plural': 'Fuqorolar',
                'ordering': ('id',),
            },
        ),
    ]
